.gitignore
CHANGES.rst
serial/__init__.py
setup.py

Use alpha status versioning for pip and tools to understand that this build is not translated to version 0.0
Use setup tools for develop mode support.

Use setup tools if available and update versioning to pep 440 compatibility,

---

serial/tools/list_ports_osx.py

Fixes parsing of USB serial number entry used by list_ports() in OS X

OSX list_ports: fixed serial number parsing

---

documentation/pyserial_api.rst

Noticed a typo in the documentation for the Serial class in the latest docs, here's a PR fixing it.

proofread Serial class doc

---

serial/serialwin32.py

In the win32 documentation for ReadFile found at:
https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365467(v=vs.85).aspx
it says:
"If hFile was opened with FILE_FLAG_OVERLAPPED, the following conditions
are in effect:
-  The lpOverlapped parameter must point to a valid and unique OVERLAPPED
structure, otherwise the function can incorrectly report that the read
operation is complete.
-  The lpNumberOfBytesRead parameter should be set to NULL. Use the
GetOverlappedResult function to get the actual number of bytes read. If
the hFile parameter is associated with an I/O completion port, you can
also get the number of bytes read by calling the
GetQueuedCompletionStatus function."
In the previous version of read the variable "rc" was set with ReadFile.
This works on windows 7 for all …

fixed issue with 0 timeout on windows 10

---

serial/aio.py

The self._sock_fd attribute references are replaced with self.serial.fd references.

Replaces erroneous references to socket with serial

---

serial/aio.py

SerialTransport ultimately inherits from asyncio.transports.BaseTransport. The existing code did not call the superclass initializer, so subsequent calls to inherited methods such as SerialTransport.get_extra_info() would fail.

Call the superclass initializer in SerialTransport.

---

serial/aio.py

This is required for compatibility of SerialTransport with Python 3.5.1, when the `is_closing()` method was introduced.
There should be no impact on backwards compatibility.

Adds an override of BaseTransport.is_closing() to SerialTransport.

---

serial/serialposix.py

The pySerial documentation states that a write_timeout setting of zero should result in non-blocking write() behaviour.  This pull-request modifies serialposix.Serial.write() to respect that requirement, by distinguishing between zero and non-zero numeric timeouts. In the zero timeout case, the underlying write() call is made and then the function immediately returns the number of bytes written, which may not be all of the data which which was passed to write.
The previous version of the code would iterate, using select(), until all data had been written, effectively blocking from the clients point of view.  True non-blocking writes are essential for a high-quality asyncio serial implementation.

Makes serialposix.Serial.write() respect non-blocking

---

serial/__init__.py

PEP396: Module Version Numbers tells us that module version numbers should be available in a `__version__` attribute.  Historically, pySerial has used VERSION instead. This commit adds `__version__` and aliases the legacy VERSION to it for backwards compatibility.
Note that although PEP396 is not yet accepted, this is a very widely followed standard and I was surprised that pySerial did not follow it.

PEP 396 compatible __version__ attribute.

---

serial/aio.py

This PR provides full implementations of all the asyncio.Transport methods in SerialTransport, including non-blocking buffered writes, protocol pausing, write-buffer high- and low-water mark configuration, robust closing and immediate abort.
I've tried hard to make the code well-factored and understandable.
Regrettably, I'm unable to provide unit tests as I'm yet to devise a robust technique for testing non-blocking asynchronous IO without using real serial hardware. This may change in future, but I'm not there yet.  That said, I've spent a lot of time running this code with various tests and submit it in good faith that it works reliably.

Non-blocking asychronous SerialTransport with write-buffering.

---

serial/threaded/__init__.py

Default connection_lost behavior swallowed all exceptions that occurred while a ReaderThread was running, sometimes making a client protocol difficult to debug. This patch instead raises an exception if one occurred.

raise ReaderThread exceptions in connection_lost

---

test/test_pty.py

Perhaps it would be convenient to add a test to avoid #59 or #76 in the future.

test: open serial on PTY

---

serial/threaded/__init__.py

FramedPacket in v3.1 raises `NameError: global name 'packet' is not defined` when it receives a packet

fix bug in FramedPacket

---

setup.py

It's bad practice for setup.py to import the package it is installing in order to get, say, version information. For example. if PYTHONPATH has been manipulated, the `import serial` statement may not in fact import the expected version.
This commit uses a technique for single-sourcing the version number as recommended in the [Python Packaging Guide](http://python-packaging-user-guide.readthedocs.io/en/latest/single_source_version/). In essence, we read `serial.__init__.py` as a text file and parse it for the version number, rather than importing it.

Avoids setup.py having to import the serial package.

---

documentation/pyserial_api.rst

I'm not sure if isOpen() has been officially deprecated, so I just marked it as such.

Added documentation for is_open and isOpen.

---

serial/threaded/__init__.py

Change append to extend in serial.threading.FramedPacket data_receive function, wich will work both under Python 2.7, and Python 3.5, without throwing and error.

Fix "TypeError: an integer is required" error from data_received.

---

serial/__init__.py

It turns out that we can't use namespace packages with pySerial, because the serial package exports names such as `serial_for_url`, and name exports from `__init__.py` are incompatible with the namespace package mechanism.
This was the reason for the failure in the new `pyserial-asyncio` package.
This is the companion pull request to PR2 in `pyserial-asyncio` which also converts that to a regular package called `serial_asyncio` which must exist side-by-side with `serial`.

serial cannot be a namespace package as it exports names

---

serial/tools/list_ports_windows.py

On windows when reading port info, get the 'manufacturer' property similar to other platforms.

Windows: list_ports with 'manufacturer' info property

---

examples/rfc2217_server.py
serial/rfc2217.py

This changeset fixes issues when passing `to_bytes()` a sequence/generator of bytes, which causes `bytearray` to raise a `TypeError` on python3. Fixes #180.

Fix python3 bytes issues when running rfc2217_server.py

---

CHANGES.rst
README.rst
documentation/examples.rst
documentation/pyserial_api.rst
documentation/tools.rst
documentation/url_handlers.rst

Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).

Fix typos in documentation

---

documentation/pyserial_api.rst
serial/__init__.py
serial/serialposix.py
serial/serialutil.py

On Linux machines, opening a serial port is non-exclusive; you can open multiple simultaneous connections to the same serial port.  This does not seem to be the case on Windows, but more the point is almost certainly not the behavior you want, various processes all stepping on one another's comm.
Unfortunately you can't just open the Serial object then fcntl.flock it because, in between, initializing the Serial port did all manner of things to settings like baud rate, timeouts, etc.  So the fix is that the call to flock has to happen immediately, right after the os.open of the raw port, before any of the termios action.
This pull adds an exclusive keyword argument to Serial.__init__ and corresponding data descriptors.  On a serialposix.Serial, setting exclusive explicitly True or False …

Exclusive access on POSIX.

---

serial/tools/list_ports_linux.py

Advantech makes multi-port PCI/PCIe to serial controllers used in industrial sorts of applications.  Their driver names the ports /dev/ttyAP*.  This pull adds that pattern to the list in serial.tools.list_ports_linux.comports()

Advantech multi-port controllers on Linux

---

serial/rfc2217.py

Although modem line status methods (like getRTC, getRI, ...) are deprecated in Pyserial 3, they are still present in rfc2217.py. Replaced methods by corresponding properties.

Changed modem line status methods to setters and getters.

---

serial/urlhandler/protocol_socket.py

On some windows machines opening a RFC 2217 connection results in an **BlockingIOError: [WinError 10035]**.  As this error is nonfatal and the operation should be retried later according to [Windows Sockets Error Codes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx) simply ignoring this exception solves the problem.

protocol_socket: Retry if BlockingIOError occurs in reset_input_buffer.

---

serial/tools/list_ports_common.py
serial/tools/list_ports_windows.py

Some USB Composite Devices will have a MI ('multiple interfaces')
parameter which indicates what is the interface number of that USB
device.
If this &MI_xx parameter is present the current regexp will not work correctly and it will not get the 'serial_number'. This will fix also that issue.

Added query also for &MI_xx parameter from HardwareID string

---

serial/tools/list_ports_linux.py

On devices with multiple serial interfaces, like FT4232,
the usb_device path is the same for all interfaces, so hwid does
not uniquely identify the interface.
So in this case use the basename of the interface directory.
Single interface:
hwid: USB VID:PID=0403:6015 SER=DN00RHW0 LOCATION=3-1.1
Multiple interface:
hwid: USB VID:PID=0403:6011 SER=FT97WK0I LOCATION=3-1.2:1.1
Signed-off-by: Eliot Blennerhassett eliot@blennerhassett.gen.nz

linux: list_ports use interface path for multi location

---

serial/serialutil.py
test/test_context.py

Hi,
I got the issue when I was doing something like:
import serial
port = serial.Serial(
port='COM4',
baudrate=115200,
bytesize=8,
parity=serial.PARITY_NONE,
stopbits=1,
timeout=2)
with port as stream:
stream.write(b'1234')
with port as stream:
stream.write(b'5678')

serial: SerialBase with is idempotent

---

serial/tools/list_ports_common.py
serial/tools/list_ports_linux.py

See #262
Set the default `ListPortInfo.name` attribute from the full `device` name,
using `os.path.basename(device)`
This should be valid for all platforms, but can be easily overridden in
platform specific code that populates the `ListPortInfo` object.

list_ports: set default `name` attribute

---

serial/rfc2217.py

Return an empty bytes object when the rfc2217 connection closes. This way the behavior is the same as closing a normal serial port.

return b'' when connection closes on rfc2217 connection

---

serial/__init__.py
serial/rfc2217.py
serial/rs485.py
serial/serialcli.py
serial/serialjava.py
serial/serialposix.py
serial/serialutil.py
serial/serialwin32.py
serial/threaded/__init__.py
serial/tools/hexlify_codec.py
serial/tools/list_ports.py
serial/tools/list_ports_common.py
serial/tools/list_ports_linux.py
serial/tools/list_ports_osx.py
serial/tools/list_ports_posix.py
serial/tools/list_ports_windows.py
serial/tools/miniterm.py
serial/urlhandler/protocol_alt.py
serial/urlhandler/protocol_hwgrep.py
serial/urlhandler/protocol_loop.py
serial/urlhandler/protocol_rfc2217.py
serial/urlhandler/protocol_socket.py
serial/urlhandler/protocol_spy.py
serial/win32.py

This prevents Python 2.7 from attempting -- and failing -- to import system modules like sys and ctypes from the ``serial/`` directory.
At the company I work for, we're running Python 2.7 instances from a Windows share. Absolute imports in our production software have reduced system module import misses by 1000 per run. I'm going through third-party modules to further reduce the import misses. =)
Please let me know if you see anything out of place or need me to make any changes to get this patch accepted! I ran the unit tests on Windows and they continued to pass but let me know if I missed something. Thanks!

Use absolute import everywhere

---

documentation/pyserial.rst

Checked the version against conda today, looks like it's pyserial 3.4.
```
In [1]: import serial
In [2]: serial.__version__
Out[2]: '3.4'
```

Update conda version in pyserial.rst

---

serial/tools/miniterm.py

The MiniTerm.writer() method expects the exit_character and menu_character in character format instead of integer.
The main() function works because both member variables are overwritten with the correct format, any other programs using the default values from the constructor won't be able to exit or view the menu.

Fix miniterm constructor defaults for exit_character and menu_character variables

---

serial/tools/miniterm.py

Fixes #326. miniterm.py now uses exclusive access for `serial.Serial` instances by default. The new option `--non-exclusive` can be used to override the default, disabling exclusive access for native ports. No change for non-native ports.
Tested on Linux (Python 3.4.2).

miniterm.py: use exclusive access for native serial ports by default

---

documentation/pyserial_api.rst

The word 'uppon' was in the documentation twice, so I changed it to 'upon'

Fixed 'uppon' typos

---

serial/tools/list_ports_common.py

Makes it behave as consistently within unordered data structures like sets/hashes.

Make ListPortInfo hashable

---

documentation/pyserial_api.rst

Missed this on the last pull request.  Currently rendering as (‘n’ by default) instead of ('\n’ by default)

Properly escape backslash.

---

serial/serialwin32.py

Fixed the docstring for the set_buffer_size function. It should be called after the port is opened otherwise it will be overwritten

Fixed the docstring for the set_buffer_size function. 

---

serial/win32.py

This is helpful when a user wants to wait for some kind of communication event. E.g. listening for parity errors, etc.

Add WaitCommEvent function to win32

---

serial/tools/list_ports_windows.py

This pull request fixes https://github.com/pyserial/pyserial/issues/283 by adding in a device traversal up the USB device tree if a serial number is not detected at the original device node.
This allows composite USB devices to report correct serial numbers on windows.

[Windows] Serial number support for composite USB devices

---

serial/tools/list_ports_windows.py

Devices using the Window USB Modem driver use the Modem GUID instead
of the Ports GUID. Add the Modem class to the set of GUIDs to scan.
Signed-off-by: Keith Packard <keithp@keithp.com>

tools/list_ports_windows: Scan both 'Ports' and 'Modem' device classes

---

documentation/url_handlers.rst
serial/rfc2217.py
serial/urlhandler/protocol_rfc2217.py

Fixed transposed RFC 2217 (was 2271)  
Updated docs and comments incorrectly referencing 2271 (SNMP).  No code change.

Replaced RFC 2271 with 2217 in docs & comments

---

serial/rfc2217.py

When stopping the read loop, do not set `self._thread = None` inside the thread itself as there may be a race-condition with the method close().
The method close() closes the socket, which stops the read loop. When the read loop stops, it set `self._thread` to `None`, but if it sets it to `None` while close() is right between between the execution of `if self._thread:` and `self._thread.join()`, close() will raise an AttributeError.

rfc2217/close(): fix race condition

---

serial/tools/list_ports_osx.py

A number of Arm-based microcontrollers, such as the kinetis-based Teensy 3 family, provide a native USB interface that allows the user to control a number of attributes, such as the product descriptor string. However, macOS exhibits some weird behavior where it mangles specifically the product descriptor string (and as far as I can tell, only the product descriptor string) on USB serial devices (this also does not seem to happen with other types of USB device). The mangling, which replaces all non-alphanumeric characters with underscores, appears to happen somewhere deep in the kernel's BSD serial subsystem. In order to work around this, the device's product name can be queried with a different IOKit call, specifically `IORegistryEntryGetName`, which appears to be aliased directly to the …

macOS: rework list_ports to support unicode product descriptors.

---

serial/__init__.py
serial/serialposix.py

Fixes #366 
These values were pulled from the system <ioctl.h> headers on mac. As such this should allow the .break_condition to be set on mac and bsd based systems.
I implemented this functionality by duplicating the code within the two platform specific sections for 'darwin' and 'bsd'.

Mac and bsd fix _update_break_state

---

documentation/url_handlers.rst
serial/urlhandler/protocol_cp2110.py
setup.py

These two chips implement UART access via a HID protocol, which can be
implemented purely in user space. The protocol is documented by Silicon
Labs AN434:
https://www.silabs.com/documents/public/application-notes/AN434-CP2110-4-Interface-Specification.pdf
The backend is implemented based on cython-hidapi
(https://github.com/trezor/cython-hidapi), making it OS-independent, if a
bit awkward.

Add a backend for Silicon Labs CP2110/4 HID-to-UART bridge.

---

.gitignore
.travis.yml

As previously mentioned in #499 and #476 this pull request is for dropping older python versions that are not available on travis anymore

Dropping python 3.2 and 3.3

---

serial/serialposix.py

When using a custom baud rate on Linux these lines of code caused it
to push a 38400 baud rate setting down into the serial driver (even
if temporarily).  It would correct this moments later, but we can
simply set the BOTHER value at this point.  If other platforms have
a different default value for ispeed and ospeed when using a custom baud
rate, they can define BOTHER as well.

linux: Fix custom baud rate to not temporarily set 38400 baud rates

---

serial/tools/miniterm.py

This pull should enable a working terminal on Windows 10 with all main control keys supported and proper console behaviours as demonstrated by connecting to a Micropython ESP8266 Vanguard board ( https://vgkits.org/blog/vanguard/ ) over USB  like...
```
python -m serial.tools.miniterm --filter direct --eol CRLF --encoding utf-8 COM3 115200
```
This is a rollup of changes to introduce detection and configuration of ANSI support (available in Windows 10 since 2015) a fix for https://github.com/pyserial/pyserial/issues/350 and a merge of ANSI-mapping features from https://github.com/zsquareplusc/mpy-repl-tool/  ( [miniterm_mpy.py](https://github.com/zsquareplusc/mpy-repl-tool/raw/master/there/miniterm_mpy.py) ).

Working CMD.exe terminal using Windows 10 ANSI support

---

serial/tools/list_ports_linux.py

The "interface" property should be read from the "usb_interface_path"
instead of the "device_path" as the later one is a directory (e.g.
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.3/1-2.3:1.0/ttyUSB1).
This has been tested together with an CP2105EK where it is important
to separate the serial ports from each other.

Correct "interface" property on Linux hosts

---

serial/tools/list_ports_osx.py

Instead of looking up this value, use 0 instead [per IOKit documentation this is the same - https://developer.apple.com/documentation/iokit/kiomasterportdefault]
tested on Big Sur released today.

fix issue 509 - kIOMasterPortDefault no longer exported on Big Sur

---

serial/tools/list_ports_osx.py

added call to get IOUSBHostDevice before falling back to
IOUSBDevice (which has been removed on Big Sur on Apple Silicon)
Thanks to @oskay for this patch.

fix issue 545 - getting USB info on BigSur/AppleSilicon

---

serial/serialposix.py

If an exception occured during _update_dtr_state(), the Serial object
was left in an inconsistent state: is_open=True, but close() fails.
This patch fixes this by not setting is_open to True and by cleaning
up the state if an exception occurs during open()
I noticed this issue, because I would sometimes get
Traceback (most recent call last):
File "mycode.py", line 159, in open
ret = self._serial.open()
File "/usr/local/lib/python3.7/dist-packages/serial/serialposix.py", line 286, in open
self._update_dtr_state()
File "/usr/local/lib/python3.7/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
on pyserial 3.4, which is likely related to replugging the device with unlucky timing.
A 3.4 …

serialposix: Fix inconstent state after exception in open()

---

serial/urlhandler/protocol_hwgrep.py
test/test_context.py

Hi,
This tiny PR will fix : 
- 1 typo in `serial/urlhandler/protocol_hwgrep.py`
- 1 typo in `test/test_context.py`
Bye! :robot:

docs: fix typos

---

serial/tools/list_ports_linux.py
serial/tools/list_ports_posix.py

In case there are any symlinks which name matches any of the previously
checked globs then list_ports(include_links=True) will report them twice.
For example if there's a symlink named /dev/ttyUSB_mylink then it would
appear twice.
The problem is fixed by storing the found paths in a set instead of a list.
Documentation at https://pythonhosted.org/pyserial/tools.html#module-serial.tools.list_ports
already states that "Items are returned in no particular order" so there's
no need to do extra sorting before returning the results.
The changes have been tested on Ubuntu (using list_ports_linux.py).

Fix duplicate comports listed with list_ports(include_links=True)

---

documentation/pyserial_api.rst

Really enjoying the changes `pyserial` made through the last decade. Kudos!
Wanted to make a small contribution myself, so I made a little spellcheck change. And while I'm not a native speaker, this way it sounds clearer to me. "as expected" sounds to me like "similar or equal to what you should expect", but here it means that you might expect 800 bytes and just receive 300.

Spellcheck

---

serial/tools/miniterm.py

When asking the user for a serial port to use, the prompt line ends up in stdout, while all other information is written to stderr. If stdout is being redirected (e.g. `pyserial-miniterm | grep expression`, `pyserial-miniterm >> console.log`), the query line ends up in the redirected stream, not on the interactive output.
https://github.com/pyserial/pyserial/blob/9e3b4f364aa50bd62d3044ed0d5221bd42a1c1f4/serial/tools/miniterm.py#L375
This commit fixes that.

Redirect Minicom's Port Prompt to stderr

---

serial/serialposix.py

Fixed the issue where a custom baudrate could not be set for the MIPS platform.
The hard coded values in the IOCTL call do differ in MIPS when compared to most other platforms.
This problem manifested itself on the OpenWRT platform where most of the smaller router devices are using a MIPS processor. Trying to open a port with a speed of 250k baud would result in the error message "not a tty".  This is fixed now with this pull request.

Add support for setting a custom baudrate on the MIPS platform

---

CHANGES.rst
examples/wxTerminal.py
serial/rfc2217.py
serial/threaded/__init__.py
serial/tools/hexlify_codec.py
serial/tools/list_ports_osx.py
serial/tools/list_ports_windows.py
test/test.py
test/test_timeout_class.py

Found via `codespell -q 3 -L ba,ser,wont`  
First identified from a downstream project that uses the pyserial lib

Fix misc. documentation and source comment typos

---

documentation/shortintro.rst

Hi devs, thanks for the work on pyserial! Miniscule fix in the docs. `\n` was not in inline mode, causing the backslash to be escaped: https://pyserial.readthedocs.io/en/latest/shortintro.html#readline. Fixed by adding backticks:

Docs: \n was not in inline mode, causing the backslash to be escaped

---

serial/serialutil.py
test/test_close.py

Inheriting from `RawIOBase` means we inherit its finalization behavior, whereby `close()` is called if `.closed` is `False`. Because `Serial` does not implement `.closed`, we get the `RawIOBase` implementation which does not reflect the fact that Serial can be opened/closed multiple times.
We now provide a `.closed` property which reflects `.is_open`. This way, if `Serial` thinks it is closed, `RawIOBase` will not call `close()` again.
This also implements `close()` to override `RawIOBase.closed`, as `RawIOBase` can only be closed once.
Fixes #670

Override RawIOBase.close() and .closed

---

serial/tools/list_ports_windows.py

When using a Composite device connected to a USB-Hub (e.g. HP-Docking Station) the location string is longer than the previous buffer of 250. This then fails to extract the correct string. Doubling the buffer size got it to work as expected!

Allow for longer location Strings.

---

serial/tools/miniterm.py

Extend miniterm.main() with default_eol='CRLF' argument

Allow passing default end-of-line (eol) terminator to miniterm.main()

---

examples/wxTerminal.py
serial/rfc2217.py
serial/urlhandler/protocol_cp2110.py
test/test.py

The camelcase methods were deprecated in Python 3.10 in https://github.com/python/cpython/pull/25174

Fix threading module related DeprecationWarning.

---

documentation/pyserial_api.rst

Some minor ref correction (`ref:` -> `:ref:`)

Fix a couple of documentation links
